### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory in Lock file in windows10

### ISSUE THREAD

**Issue by chungyan5** [cjnaz/rclonesync-V2#28]
hi 

i got this error when i first time use this rclonesync-V2. 
```
2019-07-07 09:16:56,202:  ***** BiDirectional Sync for Cloud Services using rclone *****
Traceback (most recent call last):
  File "C:\Portable\rclonesync\rclonesync.py", line 730, in <module>
    if request_lock(sys.argv, lock_file) == 0:
  File "C:\Portable\rclonesync\rclonesync.py", line 539, in request_lock
    with open(lock_file, 'w') as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/tmp/rclonesync_LOCK_xxxxxx_xxxxxx__xxxxxx_xxxxxx__xxxxxx__xxxxxx_xxxxxx_'
```

i find it is hardcode of temporary file at C:/tmp/
So i suggest to add this module:
```
import tempfile
...
    if os_platform == 'Windows':
        lock_file = tempfile.gettempdir() + "/rclonesync_LOCK_" + lock_file_part
...
```

thanks
chungyan5

**Comment by cjnaz** [comment]
Thanks.  The reader says that the C:\tmp directly must be manually
created.  Your code looks interesting.   I'll check it out.

**Comment by silenceleaf** [comment]
I vote  @chungyan5 's solution, rather than create c:\temp manually

**Comment by cjnaz** [comment]
Changed in V2.8.  Thanks for the suggestion.
